# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Confetti < Formula
  desc ""
  homepage "https://confetti-cms.com"
  version "0.4.13"

  on_macos do
    url "https://github.com/confetti-cms/client/releases/download/0.4.13/client_0.4.13_darwin_all.tar.gz"
    sha256 "2bf85d2457ec415f87d6ad19333c15fe2a740795dc63e3a62043a77612b3e9b5"

    def install
      binary: confetti
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/confetti-cms/client/releases/download/0.4.13/client_0.4.13_linux_arm64.tar.gz"
      sha256 "f8f9cd150aab8443228cc1e3dfaeb9fef02a82195d42fa7ea79fd1cdeea6c358"

      def install
        binary: confetti
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/confetti-cms/client/releases/download/0.4.13/client_0.4.13_linux_amd64.tar.gz"
      sha256 "4ecd5d10a1eda47ed4eeb52913d51c2ddeca4151f9776d8729d6f90b157e7c64"

      def install
        binary: confetti
      end
    end
  end
end
